version: "3.8"

services:
  fastapi:
    env_file:
      - .env
    build: ./fastapi
    ports:
      - "127.0.0.1:8000:8000"
    container_name: fastapi
    volumes:
      - ./fastapi/blacklisted_proxies:/fastapi/blacklisted_proxies 